version: '2'
services:
  web:
    build: .
    command: mix phoenix.server
    ports:
      - 4000:4000
    volumes:
      - .:/code
    depends_on:
      - db
    environment:
      MIX_ENV: dev
      POSTGRES_ADDRESS: db
      POSTGRES_DATABASE: vuechat_dev
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
